name: Monitor Amul Product Availability

on:
  # Runs every 30 minutes, 24/7
  schedule:
    - cron: "0,30 * * * *"
  # Allow manual triggering
  workflow_dispatch:

jobs:
  monitor:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests
          pip install playwright
          playwright install chromium

      - name: Run monitor script
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: python monitor.py

      - name: Upload debug artifacts
        uses: actions/upload-artifact@v4
        if: always()  # Always upload, even if script fails
        with:
          name: debug-artifacts
          path: |
            monitor_steps.txt
            final_page.html
            step1_launched_page.png
            step2_pincode_typed.png
            step3_modal_closed.png
          retention-days: 7
